on: push
jobs:
  release_binary:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
        include:
          - target: aarch64-unknown-linux-gnu
            runs_on: ubuntu-latest
            artifact: jtd-codegen
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cross
      - run: cross build --package jtd_codegen_cli --release --target=$TARGET
        env:
          TARGET: ${{ matrix.target }}
      - run: zip --junk-paths $TARGET.zip target/$TARGET/release/$ARTIFACT
        env:
          TARGET: ${{ matrix.target }}
          ARTIFACT: ${{ matrix.artifact }}
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        env:
          TARGET: ${{ matrix.target }}
          ARTIFACT: ${{ matrix.artifact }}
        with:
          name: zip
          path: $TARGET.zip
